### ISSUE TITLE
Creative commons license

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/cologne-stardict#1]
In the stardict versions of cologne dictionaries, how is the creative commons license of the Cologne dictionaries being  handled?

Here is the relevant part (I think) of the licensing that is present in the accheader.xml file for  acc dictionary in the availability section
```
All rights reserved other than those granted under the Creative Commons Attribution Non-Commercial 
Share Alike license available in full at <ref target="http://creativecommons.org/licenses/by-nc-
sa/3.0/legalcode">http://creativecommons.org/licenses/by-nc-sa/3.0/legalcode</ref>, and summarized 
at <ref target="http://creativecommons.org/licenses/by-nc-sa/3.0/">http://creativecommons.org/licenses/by-nc-sa/3.0/</ref>.  
Permission is granted to build upon this work non-commercially, as long as credit is explicitly 
acknowledged exactly as described herein, and derivative work is distributed under the same license.
```
To me, the key phrases are:
* as long as credit is explicitly acknowledged exactly as described herein
* derivative work is distributed under the same license 

Probably, when you decide how to fulfill this in the stardict context, we should pass it by Thomas and Peter to see if they concur.   

Maybe I should raise the question with Peter, as he may already have some ideas on this.

**Comment by gasyoun** [comment]
> Probably, when you decide how to fulfill this in the stardict context, we should pass it by Thomas and Peter to see if they concur.

Makes sense. The father and the godfather.

**Comment by drdhaval2785** [comment]
On 21 Apr 2017 01:20, "funderburkjim" <notifications@github.com> wrote:

In the stardict versions of cologne dictionaries, how is the creative
commons license of the Cologne dictionaries being handled?

Here is the relevant part (I think) of the licensing that is present in the
accheader.xml file for acc dictionary in the availability section

All rights reserved other than those granted under the Creative
Commons Attribution Non-Commercial
Share Alike license available in full at <ref
target="http://creativecommons.org/licenses/by-nc-
sa/3.0/legalcode
<http://creativecommons.org/licenses/by-nc-sa/3.0/legalcode>">http://creativecommons.org/licenses/by-nc-sa/3.0/legalcode</ref>,
and summarized
at <ref target="http://creativecommons.org/licenses/by-nc-sa/3.0/">http://creativecommons.org/licenses/by-nc-sa/3.0/</ref>.
Permission is granted to build upon this work non-commercially, as
long as credit is explicitly
acknowledged exactly as described herein, and derivative work is
distributed under the same license.

To me, the key phrases are:

   - as long as credit is explicitly acknowledged exactly as described
   herein
   - derivative work is distributed under the same license


Stardict readers dont allow reading of full files. Only headwords are
accessible. I propose we keep the whole text of licence into a headword
'LICENCE'. Does it sound a good idea? A person can key in this intuitive
word and the terms of licence can be visible to him.



Probably, when you decide how to fulfill this in the stardict context, we
should pass it by Thomas and Peter to see if they concur.

Maybe I should raise the question with Peter, as he may already have some
ideas on this.


Sure. Please. Once you are OK with this, I will make an announcement.

**Comment by drdhaval2785** [comment]
@fundetburkjim,

Does this sound a good idea? I have implemented the code. If this is approved, I can incorporate in the stardict files ASAP.

.babylon files have LICENCE as the first item and hence easily accessible. Stardict files have LICENCE as headword and typing it will bring licence text to the notice of user.

**Comment by vvasuki** [comment]
>‌ I propose we keep the whole text of licence into a headword
'LICENCE'. 

Alternately, we can just include the LICENCE file in the tar.gz file we distribute. (You'd just need to place it in the dictionary folders, and I would need to make a minor modification in my script.) You're only obliged to distribute the license with derivative work (ie tar.gz file), not anything more.

**Comment by funderburkjim** [comment]
I'll pass this idea by Thomas and Peter ( i.e. have the full license under  License headword)

Some minor issues/questions:
* The license has xml tags -- is there any problem with showing these in colordict?  
* Would the line-breaks of the full license be honored by the viewer? Or should some minor coding
   adjustment be added for such a formatting purpose?
* A minor variant might be to have the License headword begin with a space -- under the assumption that this would be seen at least upon first usage of a dictionary.  
* Does Colordict/stardict format support an 'about' section?  When I looked at wordnet in colordict, I didn;'t see any provenance (about) section in the menus.

**Comment by vvasuki** [comment]
> The license has xml tags -- is there any problem with showing these in colordict?

Good point - @drdhaval2785  may need to strip these.

> Would the line-breaks of the full license be honored by the viewer? Or should some minor coding
adjustment be added for such a formatting purpose?

<BR> can be used for line break.

>‌ Does Colordict/stardict format support an 'about' section? When I looked at wordnet in colordict, I didn't see any provenance (about) section in the menus.

Not that I know of.

> A minor variant might be to have the License headword begin with a space -- under the assumption that this would be seen at least upon first usage of a dictionary.

What you're up to, gentlemen, is a bit semantically ugly. Every other headword in the dictionary is a real sanskrit or english headword. Except for this (and a few better identifiable ones). One looking up the term "LICENCE" would expect to see the meaning in sanskrit - not a clutter of legal documents. Similarly, a program mining these dicts would want real (not fake) headwords.

My personal preference is that you just bundle the LICENCE file with the tar.gz being distributed and leave it at that - that's what nearly every program on my computer does - no need to include it in the UI or anything.

But if you chose to go down this route, please prepend it with _. The reason is that several such dummy keywords are in use - for example @damoo has used keywords like _vei1_pn028 to catch all headwords in  page 28 of veda index. That way, this can be identified (by other programs as well as users) for what it is - a fake headword. Users can still look it up by typing LICENCE - autosuggest in goldendict desktop includes _LICENSE as well - so no problem.

**Comment by drdhaval2785** [comment]
> Regarding .tar.gz having the LICENCE.txt file 
I am agreeable to this too (as an addition).

> LICENCE to _LICENCE
I tried with stardict for linux and colordict for android. Autosuggest doesn't give _LICENCE when I type LICENCE.
So it is highly unlikely that actually anyone will be able to read the licence text.

> One looking up the term "LICENCE" would expect to see the meaning in sanskrit - not a clutter of legal documents.

I saw. None of our English - Sanskrit dictionary has this headword.
Seems reasonable to keep headword as `LICENCE.txt` or `LICENCE.xml`.
Will be easily distinguishable from `LICENCE` and person will have fair idea that it is going to be a text document for licence.

> Strip tags from XML.

I tried in stardict for linux. It is rendered well. No need to strip tags or do modification.
If some machine gives some errors, we will do the labor.
See

![screenshot from 2017-04-28 12-37-40](https://cloud.githubusercontent.com/assets/5755132/25518000/7dd7c5ca-2c0f-11e7-8e61-3d45f5f419c5.png)

**Comment by vvasuki** [comment]
> I tried with stardict for linux and colordict for android. 

I see - it worked fine on goldendict desktop and android.

> Autosuggest doesn't give _LICENCE when I type LICENCE. So it is highly unlikely that actually anyone will be able to read the licence text. ... Seems reasonable to keep headword as LICENCE.txt or LICENCE.xml

Well then, lets add an underscore to the end. We need a uniform way of determining fake keywords - inclusion of an underscore (preferably starting with it) is the current convention.

**Comment by vvasuki** [comment]
Also -

>None of our English - Sanskrit dictionary has this headword (it can show up in computer-shrIkAnta or wiktionary). 

No one can predict the future - or even the present for that matter.

 here is what I get on my dict right now. 


```

From borooah
license

LICENSE (subs.):
²I Permission: अनुज्ञा।
²II Its document: अनुज्ञापत्रम् (?).
²III Excess of liberty: अनियन्त्रणा (?). Ph.:
poets have free l.: निरङ्कुशाः कवयः, S.k.
license

LICENSE (v.): अनुजानाति (ज्ञा, c. 9.): v. To permit.
From mw-english-sanskrit
license

LICENSE, s. (Leave, permission) अनुज्ञा, अनुमतिः f., अनुज्ञानं, अभ्यनुज्ञा, समनुज्ञानं, क्षमता, आज्ञा; ‘written license,’ अनुज्ञापत्रं, आज्ञापत्रं
--(Excess of liberty) मर्य्यादातिक्रमः, व्यतिक्रमः, अनर्गलता, उत्क्रमः, विधिव्यतिक्रमः, विधिनिषेधातीतता.
license

To LICENSE, v. a. अनुज्ञापत्रेण अनुमन् (c. 4. -मन्यते -मन्तुं), अनुज्ञा (c. 9. -जानाति -नीते -ज्ञातुं), अनुज्ञां दा, अनुज्ञापत्रं दा, आज्ञापत्रं दा.
From spokensanskrit
license

स्थानीयानुमति	sthAnIyAnumati	f.	site license   [ computer ]
स्थानीयाज्ञापत्र	sthAnIyAjJApatra	n.	site license   [ computer ]
तन्त्रांशाज्ञापत्र	tantrAMzAjJApatra	n.	software license   [ computer ]
From wiktionary_kn
License

ಪದ : License
—————————————————————————
ಭಾಷೆ : ಚಿಚೇವ
│☘ಹೆಸರುಪದ│
—————————————————————————
License
 1. ಪರವಾನಗಿ
license

ಪದ : license
—————————————————————————
ಭಾಷೆ : ಇಂಗ್ಲೀಷ್
│☘ನಾಮಪದ│
—————————————————————————
license
 1. ಅನುಮತಿ, ಅಪ್ಪಣೆ, ಅನುಜ್ಞೆ
 2. ಅಧಿಕಾರ ಪತ್ರ, ಸನ್ನದು, ಅಪ್ಪಣೆ ಚೀಟಿ, ಪರವಾನಗಿ, ಪರ್ಮಿಟ್ಟು, ಲೈಸನ್ಸು
 3. ಸ್ವಚ್ಛಂದ ವೃತ್ತಿ, ಸ್ವೇಚ್ಛಾ ವರ್ತನೆ, ಸ್ವಾತಂತ್ರ್ಯದ ದುರುಪಯೋಗ
 4. ಸೆಲವು, ಒಪ್ಪಿಗೆ
│☘ಕ್ರಿಯಾಪದ│
—————————————————————————
license
 1. ಪರವಾನಗಿ ನೀಡು, ಅನುಮತಿ ಕೊಡು
```

**Comment by gasyoun** [comment]
> No one can predict the future 

Ok, ok, so you found a few cases :face_with_head_bandage:

**Comment by funderburkjim** [comment]
Here is another suggestion that occurred both to Peter and to me.
The way Peter phrased it:
> the terms of the license should also be explicitly stated in the description of the app in the app store 
with a link to the full license.

The way I would say it is that  it would be useful to have an enhancement to Stardict Dictionary Updater.

The enhancement could be on the page where a user selects a particular dictionary from a list  (like where Macdonell is chosen).   At that point, there would be a display of some meta-data that pertains to the dictionary.  Since we are thinking about license meta-data,  there would be some brief statement that the data is made available by X under a license Y, and a link to a full display of the license   (this could
be a link to a location within the GitHub Pages for Stardict).  The license should probably also be part of the tar file of the dictionary.

Other meta data might include:
- a link to the website from which the dictionary data is drawn
- the date of the dictionary file

If this approach were adopted, it would avoid the somewhat hokey use of a 'LICENSE' headword; and
would provide a structured way for SDU to acknowledge the open-source contribution of the dictionary providers.

Such information would be useful for all the dictionaries managed by the Stardict Dictionary Updater,
not just for those from the Cologne Sanskrit Lexicon.
For instance, I think there is an amarakosha in Stardict Dictionary Updater collection.  When using this, I would like to know where the dictionary data comes from (its provenance) --- e.g. is it from Sanskrit Documents web site, some collection from Hyderabad, or where?  I might like to visit the website from which the dictionary originates, and see what other kinds of things are there.

In a way,  the service being provided by the Stardict Dictionary Updater seems analogous to the service provided by such software repositories as the [Python Package Index](https://pypi.python.org/pypi).  Maybe perusal of this or similar sites would give other suggestions to SDU.

**Comment by vvasuki** [comment]
> The license should probably also be part of the tar file of the dictionary.

This is easily achievable - and makes sense if this dummy headword route is dropped. It's up to you and dhaval what you pick. My only concern is the inclusion of an underscore if the latter is chosen.

> The enhancement could be on the page where a user selects a particular dictionary from a list (like where Macdonell is chosen). At that point, there would be a display of some meta-data that pertains to the dictionary. Since we are thinking about license meta-data, there would be some brief statement that the data is made available by X under a license Y, and a link to a full display of the license (this could
be a link to a location within the GitHub Pages for Stardict).

The main issue with this is a philosophical problem (that too without getting into the "lawyers society" vs "customs society" or "spirit" vs "letter" issues). This will not achieve what you want universally because dicts that result from cologne-stardict will not (and will never) be installed using any one given route (the android updater app). Users can and do manually download (desktop, iphone or even android) and add the dict they want, or use scripts like <https://github.com/nangia/pydictupdater>. This trouble you would go to with the stardict updater app will be wasted in these other cases.

So, *it doesn't make sense to single out the updater app* - you should think of this more modularly. Forget (more or less) the apps. Think of it as a transaction between the cologne xml repo and the stardict-sanskrit repo. Once the stardict dictionaries are produced, packaged and submitted to the stardict-sanskrit  repo in a satisfactory way (ie including license etc..), you're done. It's up to the apps or users who in turn use the stardict-sanskrit repo to continue to honorable include the license in the packages they distribute. This is more or less a given because it does not make sense to go the trouble of selectively removing the license info once it's in the package in  stardict-sanskrit repo.

Apart from this there are other problems with this proposal:
* UI Issues: You might have observed that screen is already quite cluttered with all sorts of info about each dict (its category, name, date, size). Adding yet another link (let alone a "made available by X under a license Y" sentence ) makes it worse.
* Implementation issues: Technically, this will have to be achieved in a round-about manner - in order to retain backward compatibility, I cannot change the structure of the data the app reads from github. That makes about thrice as much work (separately read a "dictionary to info link table" online, then link to it). This low unattractive reward/ result ratio makes a loooong delay before it gets implemented.

An alternate (easier) route is that I can add a prominent message in the updater app (example in the final screen) guiding users as to how they can find the appropriate license and other info for each dictionary.

**Comment by vvasuki** [comment]
>> The license should probably also be part of the tar file of the dictionary.

>‌This is easily achievable - and makes sense if this dummy headword route is dropped. It's up to you and dhaval what you pick. My only concern is the inclusion of an underscore if the latter is chosen.

Thinking a bit further, I find that the dummy headword technique is even less appealing. Reason is this - we can't expect a skillful and careful dhaval to come by and create a dummy headword for every non-cologne dictionary we add. So, in one dystopian vision of the future we could end up having some licenses as dummy headwords and others as LICENSE files and downstream apps would have to provide confusing and verbose instructions to the users about how to see the license data. We should just standardize and stick to including the LICENSE file in our tar.gz archives.

**Comment by gasyoun** [comment]
> (example in the final screen)

Where?

**Comment by vvasuki** [comment]
>> (example in the final screen)

>Where?

Ah. I mean to say: for example in the final screen. Fixed my post.

**Comment by funderburkjim** [comment]
Here is the main part of Peter's response to the 'license headword notion'  just for the record. 
```
	I’m all in favor of making the dictionaries available in apps.  Yes including the license in a headword 
seems fine.  However, the terms of the license should also be explicitly stated in the description of the 
app in the app store with a link to the full license.
	It would also, I think, be a good project to make a single app of the Sanskrit Library interface where 
all dictionaries can be combined in a single search and different results found by clicking on the 
dictionary link.  But that may be another project.
	How much will the app cost?  Or is the intention to give it away free?  If there is a cost, that means it is 
commercial, is not covered by the Creative Commons license, and a separate license has to be negotiated 
with Cologne (Thomas) and the Sanskrit Library (me).

```
and to the 'include license in tar' idea.
```
Fine to do this too.  The main thing is that it should (a) be there and (b) be accessible and (c) be known to whoever downloads it.
```

**Comment by funderburkjim** [comment]
> add a prominent message in the updater app  ...

It sounds like this alternate, along with inclusion of  license file within the tar,  might be a good
solution . It seems likely to provide provenance and attribution information, on the one hand,  and
not impose an inordinate burden on  @vvasuki  and other stardict updater developers.

**Comment by gasyoun** [comment]
> one hand, and
not impose an inordinate burden

Exactly.

**Comment by vvasuki** [comment]
>‌ It sounds like this alternate, along with inclusion of license file within the tar, might be a good
solution .

Cool! Sounds like a plan! Once @drdhaval2785 puts those LICENSE.md files (<-- Note the standard filename) in the particular dictionary-specific directories, I will then fix my scripts to include them in the generated tar.gz files and insert a "you can look at the license files in location X (for example by doing Y)" message in the updater app.

> It would also, I think, be a good project to make a single app of the Sanskrit Library interface where 
all dictionaries can be combined in a single search and different results found by clicking on the 
dictionary link. How much will the app cost?  Or is the intention to give it away free?  If there is a cost, that means it is commercial, is not covered by the Creative Commons license, and a separate license has to be negotiated with Cologne (Thomas) and the Sanskrit Library (me).

That sounds, frankly, horrid and ominous. For one thing, it cannot possibly cover all possible devices and for another - ends up "reinventing the wheel". That's a sure way to loose users and encourage them to find other routes to achieve their ends.

**Comment by funderburkjim** [comment]
I mentioned to Peter how the dictionaries can be combined in lookup with Colordict, and he seemed satisfied with this solution to multiple-dictionary functionality.

**Comment by funderburkjim** [comment]
> LICENSE.md   

The 'md' usually means 'markdown'. 

@vvasuki   Should we prepare a transformation of our xml header files to markdown?

e.g., for ACC dictionaray , should we convert  our [accheader.xml](http://sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/pywork/accheader.xml) to a LICENSE.md ? [One way would be
just to include the xml within a pair of triple single quotes].
And then include that LICENSE.md file in the tarball for ACC?

**Comment by vvasuki** [comment]
> I mentioned to Peter how the dictionaries can be combined in lookup with Colordict, and he seemed satisfied with this solution to multiple-dictionary functionality.

Good to know ~ I was initially alarmed at the possibility of the data becoming unavailable (as in case of DSAL) after such a license change, but later was not sure if that was meant.

> The 'md' usually means 'markdown'.
> @vvasuki Should we prepare a transformation of our xml header files to markdown?

MD (even looking at just the source) is more human-readable than xml, which is why I settled on it. So, the licenses will look good on Github, as well as in the phone using just a text viewer. So, if you wish to make your licenses more readable and have time for it, go ahead and convert to md - if not, it is fine for now to just dump your xml-s in those files (I don't think that users are eagerly awaiting license files! ).

> And then include that LICENSE.md file in the tarball for ACC?

@drdhaval2785 's scripts should just dump the LICENSE.md file along with the babylon file (as it currently does) in the appropriate directory. My stardict/ tarball generating scripts will take care of everything after that.

**Comment by drdhaval2785** [comment]
Currently the files licence.xml are shipped along with stardict files. I checked up in my mobile phone. The location of the licence.xml is as sibling to the XXX.dict.dz / .syn / .ifo and .idx files.

**Comment by funderburkjim** [comment]
Sounds good.
