### ISSUE TITLE
Fix correction link in stardicts

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-lexicon/cologne-stardict#38]
> In that case csl-devanagari repository is the best place. You can generate PR there. I will fetch it to csl-orig.

इति [धवलः](https://github.com/sanskrit-lexicon/csl-ldev/pull/21)।  @drdhaval2785 

तथा चेत् प्रत्येकस्मिन् कोशय् एतादृशास् सङ्केताः परिवर्त्यन्ताम्।

![image](https://github.com/sanskrit-lexicon/cologne-stardict/assets/2664797/a975f1d0-12e9-40be-a367-dbcf3e25e690)

**Comment by drdhaval2785** [comment]
Dear friends,
The structure is something like this. 
1. csl-orig holds data (in SLP1) which is used by Cologne
2. csl-devanagari holds the same data (in Devanagari)
3. csl-ldev holds csl-devanagari split entry wise (Lnum wise Devanagari data)
4. csl-lnum holds csl-orig data split entry wise.

Currently I have shown csl-ldev links for correction, so that the user is not bogged down by large files. He lands at csl-ldev of the entry under consideration which he wants to correct.

I don't think people at large would be so tech savvy as to navigate large files and search the entry they want to correct.

Let me know if the users think otherwise.

**Comment by vvasuki** [comment]
> Currently I have shown csl-ldev links for correction, so that the user is not bogged down by large files. He lands at csl-ldev of the entry under consideration which he wants to correct.

Seems to be best as it is then.
